{ -------------------------------------------------------------------- }

{$DEFINE SPREADSHEET}
//SPREADSHEET creates VAL file design form
//  This uses the spread.* and design.* files

//{$DEFINE OLDSTATS} //{$DEFINE OLDSTATS}
// OLDSTATS did caused some non-random permutations
// Only use oldstats to replicate the problem

{$DEFINE NEWRNG}
// NEWRNG enables a better (but slower) random number generator


//{$DEFINE MY_DEBUG} //{$DEFINE MY_DEBUG}
// MY_DEBUG allows npmform to automatically run analyses at startup



